// examples/frameworks/vue/src/App.vue
<template>
  <div style="height: 100vh; display: flex; flex-direction: column">
    <div
      :style="{
        padding: '16px',
        backgroundColor: status.color,
        color: 'white',
        fontSize: '20px',
        textAlign: 'center',
        fontWeight: 'bold',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center'
      }"
    >
      <div style="flex: 1">{{ status.text }}</div>
      <button
        v-if="status.text.includes('Found')"
        @click="resetMap"
        style="
          padding: 8px 16px;
          background-color: rgba(255, 255, 255, 1);
          color: black;
          border: 1px solid white;
          border-radius: 4px;
          cursor: pointer;
          font-size: 14px;
          margin-left: 16px;
        "
      >
        Reset
      </button>
    </div>
    <div ref="mapContainer" style="height: 100%; width: 100%" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import { geoai, type ProviderParams } from 'geoai'
import MaplibreDraw from 'maplibre-gl-draw'
import 'maplibre-gl-draw/dist/mapbox-gl-draw.css'

const mapProviderConfig = {
  provider: 'esri',
  serviceUrl: 'https://server.arcgisonline.com/ArcGIS/rest/services',
  serviceName: 'World_Imagery',
  tileSize: 256,
  attribution: 'ESRI World Imagery'
}
const inferenceZoomLevel = 15 // The zoom level at which the inference will be run

const mapContainer = ref<HTMLDivElement | null>(null)
const map = ref<maplibregl.Map | null>(null)
const drawRef = ref<MaplibreDraw | null>(null)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const pipeline = ref<any>(null)
const status = ref({ color: '#9e9e9e', text: 'Waiting...' })

onMounted(async () => {
  if (!mapContainer.value) return

  // Initialize map
  map.value = new maplibregl.Map({
    container: mapContainer.value,
    style: {
      version: 8,
      sources: {
        satellite: {
          type: 'raster',
          tiles: [
            'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
          ],
          tileSize: 256,
          attribution: 'ESRI World Imagery'
        }
      },
      layers: [{ id: 'satellite', type: 'raster', source: 'satellite' }]
    },
    center: [56.35167998561383, 25.209461334530914],
    zoom: 15
  })

  const draw = new MaplibreDraw({
    displayControlsDefault: false,
    controls: { polygon: true, trash: true }
  })
  // @ts-expect-error - MaplibreDraw types don't match addControl signature
  map.value.addControl(draw)
  drawRef.value = draw

  // Make controls bigger
  const style = document.createElement('style')
  style.textContent =
    '.maplibregl-ctrl-group button { width: 50px !important; height: 50px !important; font-size: 20px !important; } .maplibregl-ctrl-group { border-radius: 8px !important; }'
  document.head.appendChild(style)



  // Initialize pipeline
  try {
    status.value = { color: '#ffa500', text: 'Initializing AI Model...' }

    // Initialize pipeline
    const newPipeline = await geoai.pipeline(
      [{ task: 'oil-storage-tank-detection' }],
      mapProviderConfig as ProviderParams
    )
    pipeline.value = newPipeline
    status.value = {
      color: '#4caf50',
      text: 'AI Model Ready! Draw a polygon to detect oil storage tanks using the controls on the right.'
    }

    // Set up draw event listener after pipeline is ready
    map.value?.on('draw.create', async (e) => {
      status.value = { color: '#2196f3', text: 'Processing detection...' }
      try {
        // Run inference with fixed optimal zoom level
        const result = await newPipeline.inference({
          inputs: { polygon: e.features[0] },
          mapSourceParams: { zoomLevel: inferenceZoomLevel },
          postProcessingParams: {
            confidenceThreshold: 0.5,
            nmsThreshold: 0.3,
          }
        })

        // Remove existing detections (using same naming as live examples)
        if (map.value?.getSource('detections')) {
          map.value.removeLayer('detections-layer')
          if (map.value?.getLayer('detections-outline')) {
            map.value.removeLayer('detections-outline')
          }
          map.value.removeSource('detections')
        }

        // Add detections using same approach as live examples
        map.value?.addSource('detections', {
          type: 'geojson',
          data: result.detections
        })
        
        // Use bright yellow like live examples for better visibility
        map.value?.addLayer({
          id: 'detections-layer',
          type: 'fill',
          source: 'detections',
          paint: { 
            'fill-color': '#FFFF00',     // Bright yellow (like live examples)
            'fill-opacity': 0.4,
            'fill-outline-color': '#FF8C00'  // Dark orange outline
          }
        })
        
        // Add detection outline for better visibility
        map.value?.addLayer({
          id: 'detections-outline',
          type: 'line',
          source: 'detections',
          paint: { 
            'line-color': '#FF8C00',    // Dark orange outline 
            'line-width': 2,
            'line-opacity': 0.8 
          }
        })

        status.value = {
          color: '#4caf50',
          text: `Found ${result.detections.features?.length || 0} oil storage tank${
            (result.detections.features?.length || 0) !== 1 ? 's' : ''
          }!`
        }
      } catch (error) {
        console.error('Detection error:', error)
        status.value = { color: '#f44336', text: 'Error during detection' }
      }
    })
  } catch (error) {
    console.error('Pipeline initialization error:', error)
    status.value = { color: '#f44336', text: 'Failed to Initialize Model' }
  }
})

onUnmounted(() => {
  map.value?.remove()
})

const resetMap = () => {
  // Clear drawn features using the draw reference
  drawRef.value?.deleteAll()

  // Clear detections (using correct layer IDs)
  if (map.value?.getSource('detections')) {
    map.value.removeLayer('detections-layer')
    if (map.value?.getLayer('detections-outline')) {
      map.value.removeLayer('detections-outline')
    }
    map.value.removeSource('detections')
  }

  status.value = {
    color: '#4caf50',
    text: 'AI Model Ready! Draw a polygon to detect oil storage tanks using the controls on the right.'
  }
}
</script>

<style scoped></style>

// examples/01-geobase-geoai.js-quickstart/src/App.tsx
import React, { useEffect, useRef, useState } from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { geoai, ProviderParams } from '@geobase-js/geoai';
import MaplibreDraw from 'maplibre-gl-draw';
import 'maplibre-gl-draw/dist/mapbox-gl-draw.css';

// Your config from Step 2
const config = {
  provider: "mapbox",
  apiKey: process.env.REACT_APP_MAPBOX_API_KEY,
  style: "mapbox://styles/mapbox/satellite-v9",
};

// Colorblind-friendly fill color (blue, e.g. #377eb8)
const DETECTION_FILL_COLOR = '#377eb8';

function App() {
  const mapContainer = useRef<HTMLDivElement>(null);
  const map = useRef<maplibregl.Map | null>(null);
  const [detections, setDetections] = useState<any[]>([]);
  const [modelStatus, setModelStatus] = useState<'idle' | 'initializing' | 'pipeline-ready' | 'inferencing'>('idle');
  const [error, setError] = useState<string | null>(null);
  const pipelineRef = useRef<any>(null);

  // Initialize the pipeline on page load
  useEffect(() => {
    let isMounted = true;
    setModelStatus('initializing');
    setError(null);

    (async () => {
      try {
        const pipeline = await geoai.pipeline([{ task: "building-detection" }], config as ProviderParams);
        console.log('pipeline', pipeline);
        if (isMounted && pipeline) {
          pipelineRef.current = pipeline;
          setModelStatus('pipeline-ready');
        }
      } catch (err) {
        if (isMounted) {
          setError('Failed to initialize model');
          setModelStatus('idle');
        }
      }
    })();

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    if (!mapContainer.current) return;

    map.current = new maplibregl.Map({
      container: mapContainer.current,
      style: {
        version: 8,
        sources: {
          'satellite': {
            type: 'raster',
            tiles: [`https://api.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}@2x.jpg90?access_token=${config.apiKey}`],
            tileSize: 256,
          }
        },
        layers: [{ id: 'satellite', type: 'raster', source: 'satellite' }]
      },
      center: [-117.59, 47.653],
      zoom: 18
    });

    const draw = new MaplibreDraw({
      displayControlsDefault: false,
      controls: { polygon: true, trash: true }
    });
    // @ts-ignore
    map.current.addControl(draw);

    map.current.on('draw.create', async (e) => {
      setError(null);
      setModelStatus('inferencing');
      setDetections([]);
      const polygon = e.features[0];

      try {
        // Wait for pipeline to be ready
        const pipeline = pipelineRef.current;
        if (!pipeline) {
          setError('Model not ready yet');
          setModelStatus('pipeline-ready');
          return;
        }
        const result = await pipeline.inference({
          inputs: { polygon },
          mapSourceParams: { zoomLevel: map.current?.getZoom() || 18 }
        });

        setDetections(result.detections.features || []);

        if (map.current?.getSource('detections')) {
          map.current.removeLayer('detections');
          map.current.removeSource('detections');
        }

        map.current?.addSource('detections', { type: 'geojson', data: result.detections });
        map.current?.addLayer({
          id: 'detections',
          type: 'fill',
          source: 'detections',
          paint: { 'fill-color': DETECTION_FILL_COLOR, 'fill-opacity': 0.8 }
        });
        setModelStatus('pipeline-ready');
      } catch (err) {
        setError('Error during inference');
        setModelStatus('pipeline-ready');
      }
    });

    return () => map.current?.remove();
  }, []);

  let statusMessage = '';
  if (modelStatus === 'inferencing') statusMessage = 'Detecting buildings...';
  else if (modelStatus === 'initializing') statusMessage = 'Model loading...';
  else if (modelStatus === 'pipeline-ready') statusMessage = 'Pipeline ready. Draw a polygon to detect buildings.';
  else statusMessage = '';

  return (
    <div style={{ height: '100vh', display: 'flex', flexDirection: 'column' }}>
      <div ref={mapContainer} style={{ height: '70%', width: '100%' }} />
      <div style={{ padding: '20px', height: '30%', backgroundColor: '#f5f5f5' }}>
        <h2>Building Detection</h2>
        <p>
          <span
            style={{
              color:
                modelStatus === 'initializing'
                  ? '#ffb000' // orange for initializing
                  : modelStatus === 'inferencing'
                  ? '#984ea3' // purple for inferencing
                  : modelStatus === 'pipeline-ready'
                  ? '#228833' // green for ready
                  : '#333'
            }}
          >
            {statusMessage}
          </span>
        </p>
        {error && <p style={{ color: '#e41a1c' }}>{error}</p>}
        {detections.length > 0 && (
          <p>
            <span style={{ color: '#377eb8', fontWeight: 600 }}>
              Found {detections.length} buildings!
            </span>
          </p>
        )}
      </div>
    </div>
  );
}

export default App;
